#!/bin/bash
period=3
if [ $# -gt 1 ]; then
    period=$2
    total_time=$1
elif [ $# -eq 1 ]; then
    total_time=$1
else
    echo "please provide the running time and load change period (optional)"
    echo "Usage: ./dynamic-load [time length] (load period)"
    exit 1
fi

iteration=$((total_time/period))
completed_iter=0

echo "$total_time $period $iteration"

while [ $completed_iter -lt $iteration ]; do
    iperf -c 192.168.1.1 -u -t $period -b 7m
    iperf -c 192.168.1.1 -u -t $period -b 10m
    completed_iter=$((completed_iter+2))
done
